import {
  CAM_ROUTES_NAMESPACE,
  CAM_UI_NAMESPACE,
  UI_CONTEXT_KEYS,
  UI_NODE_ARGUMENT_KEYS,
  UI_PROP_SCHEMAS,
  UI_RUNTIME_ROOTS,
  type UiPropTag,
} from "@cam/protocol"

export {
  CAM_ROUTES_NAMESPACE,
  CAM_UI_NAMESPACE,
  UI_CONTEXT_KEYS,
  UI_NODE_ARGUMENT_KEYS,
  UI_PROP_SCHEMAS,
  UI_RUNTIME_ROOTS,
}

export const UI_VERSION = "1.0.0"

export type { UiPropTag }
