import {
  CAM_ROUTES_NAMESPACE,
  CAM_UI_NAMESPACE,
  UI_CONTEXT_KEYS,
  UI_NODE_ARGUMENT_KEYS,
  UI_PROP_SCHEMAS,
  UI_RUNTIME_ROOTS,
  UI_VERSION,
  type UiPropTag,
} from "@cam/protocol"

export {
  CAM_ROUTES_NAMESPACE,
  CAM_UI_NAMESPACE,
  UI_CONTEXT_KEYS,
  UI_NODE_ARGUMENT_KEYS,
  UI_PROP_SCHEMAS,
  UI_RUNTIME_ROOTS,
  UI_VERSION,
}

export type { UiPropTag }
