version: '3.8'

services:
  nx-server:
    build:
      context: ./dapp32-nx
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
