version: '3.8'

services:
  nx-server-poc:
    build:
      context: .
      dockerfile: ./Dockerfile-POC
      args:
        - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
        - GITHUB_REPO=${GITHUB_REPO}
        - PORT=4001
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
