export type CamEvmErrorCode =
  | "CAM_CHAIN_MISMATCH"
  | "CAM_HOST_READ_FAILED"
  | "CAM_HOST_UNSUPPORTED"
  | "CAM_RESOURCE_LOAD_FAILED"
  | "CAM_RESOURCE_INTEGRITY_INVALID"
  | "CAM_RESOURCE_INTEGRITY_MISMATCH"
  | "CAM_DOCUMENT_INVALID"
  | "CAM_HASH_MISMATCH"
  | "CAM_HASH_UNSIGNED"
  | "CAM_ABI_INVALID"
  | "CAM_CONTRACT_UNBOUND"
  | "CAM_CONTRACT_INVALID"
  | "CAM_INVALID_ACCOUNT"
  | "CAM_UNKNOWN_CONTRACT"
  | "CAM_ROUTE_FUNCTION_NOT_FOUND"
  | "CAM_ROUTE_FUNCTION_AMBIGUOUS"
  | "CAM_ROUTE_FUNCTION_NOT_VIEW"
  | "CAM_ROUTE_CALL_FAILED"
  | "CAM_ROUTE_INVALID_KIND"
  | "CAM_ROUTE_INVALID_ARGUMENT"
  | "CAM_ROUTE_INVALID_RESULT"
  | "CAM_WRITE_FUNCTION_NOT_FOUND"
  | "CAM_WRITE_FUNCTION_AMBIGUOUS"
  | "CAM_WRITE_FUNCTION_NOT_MUTABLE"
  | "CAM_WRITE_FUNCTION_PAYABLE_UNSUPPORTED"
  | "CAM_WRITE_INVALID_ARGUMENT"
  | "CAM_WRITE_SIMULATION_FAILED"
  | "CAM_WRITE_FAILED"

export class CamEvmError extends Error {
  readonly code: CamEvmErrorCode
  readonly cause: unknown

  constructor(code: CamEvmErrorCode, message: string, cause?: unknown) {
    super(message)
    this.name = "CamEvmError"
    this.code = code
    this.cause = cause
  }
}
