version: '2'

services:
  nx-server-poc:
    build:
      context: .
      dockerfile: ../../poc/Dockerfile
      args:
        - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
        - GITHUB_REPO=${GITHUB_REPO}
        - PORT=4201
    ports:
      - "4201:4201"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    mem_limit: 100M
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "10"
